apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-python
spec:
  serviceName: postgres-service
  replicas: 1
  selector:
    matchLabels:
      app: postgres-python
  template:
    metadata:
      labels:
        app: postgres-python
    spec:
      containers:
        - name: postgres-python
          image: postgres
          env:
            - name: POSTGRES_PASSWORD
              value: test1234
          ports:
            - containerPort: 5432
