apiVersion: v1
kind: Service
metadata:
  name: python-api-service
spec:
  selector:
    app: python-api  # This selector matches the labels in your Python API Deployment
  ports:
    - protocol: TCP
      port: 80         # The port for accessing the service within the cluster
      targetPort: 5000 # The port your Python API container is listening on
